FROM ruby:2.4.0

ENV RAILS_ROOT /app_stage

RUN mkdir $RAILS_ROOT

WORKDIR $RAILS_ROOT

RUN apt-get update

RUN apt-get install -y nodejs

RUN apt-get install -y postgresql-client

RUN apt-get install -y unoconv

COPY Gemfile $RAILS_ROOT

COPY Gemfile.lock $RAILS_ROOT

RUN bundle install

COPY . $RAILS_ROOT

EXPOSE 4001

CMD puma -C config/puma.rb
